In this project, RFM metrics will be generated from the sales dataset of a store. 

RFM stands for Recency, Frequency and Monetary. It is a metric used for customer segmentation in CRM Analytics. Mainly, it is based on segmenting according to the purchasing habits of customers and hence developing strategies on these segments.

Recency is the last time that the customer purchased. The sooner is the better. Frequency is the total number of purchases, in this project it will be considered as the total number of the order dates. Monetary is the total earning from the customer.

In [1]:
import pandas as pd
import numpy as np
import datetime as dt

In [2]:
pd.set_option("display.max_columns", None)

In [3]:
df = pd.read_excel(r"C:\Users\PC\Documents\superstore.xlsx")

In [4]:
df.shape

(9994, 21)

In [5]:
df.head(50)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
5,6,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7,0.00,14.1694
6,7,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.2800,4,0.00,1.9656
7,8,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6,0.20,90.7152
8,9,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.5040,3,0.20,5.7825
9,10,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.9000,5,0.00,34.4700
10,11,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.1840,9,0.20,85.3092
11,12,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032,West,TEC-PH-10002033,Technology,Phones,False,911.4240,4,0.20,68.3568
12,13,CA-2017-114412,4/15/2017,4/20/2017,Standard Class,AA-10480,Andrew Allen,Consumer,United States,Concord,North Carolina,28027,South,OFF-PA-10002365,Office Supplies,Paper,Xerox 1967,15.5520,3,0.20,5.4432
13,14,CA-2016-161389,12/5/2016,12/10/2016,Standard Class,IM-15070,Irene Maddox,Consumer,United States,Seattle,Washington,98103,West,OFF-BI-10003656,Office Supplies,Binders,Fellowes PB200 Plastic Comb Binding Machine,407.9760,3,0.20,132.5922
14,15,US-2015-118983,11/22/2015,11/26/2015,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,Texas,76106,Central,OFF-AP-10002311,Office Supplies,Appliances,Holmes Replacement Filter for HEPA Air Cleaner...,68.8100,5,0.80,-123.8580
15,16,US-2015-118983,11/22/2015,11/26/2015,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,Texas,76106,Central,OFF-BI-10000756,Office Supplies,Binders,Storex DuraTech Recycled Plastic Frosted Binders,2.5440,3,0.80,-3.8160
16,17,CA-2014-105893,11/11/2014,11/18/2014,Standard Class,PK-19075,Pete Kriz,Consumer,United States,Madison,Wisconsin,53711,Central,OFF-ST-10004186,Office Supplies,Storage,"Stur-D-Stor Shelving, Vertical 5-Shelf: 72""H x...",665.8800,6,0.00,13.3176
17,18,CA-2014-167164,5/13/2014,5/15/2014,Second Class,AG-10270,Alejandro Grove,Consumer,United States,West Jordan,Utah,84084,West,OFF-ST-10000107,Office Supplies,Storage,Fellowes Super Stor/Drawer,55.5000,2,0.00,9.9900
18,19,CA-2014-143336,8/27/2014,9/1/2014,Second Class,ZD-21925,Zuschuss Donatelli,Consumer,United States,San Francisco,California,94109,West,OFF-AR-10003056,Office Supplies,Art,Newell 341,8.5600,2,0.00,2.4824
19,20,CA-2014-143336,8/27/2014,9/1/2014,Second Class,ZD-21925,Zuschuss Donatelli,Consumer,United States,San Francisco,California,94109,West,TEC-PH-10001949,Technology,Phones,Cisco SPA 501G IP Phone,213.4800,3,0.20,16.0110
20,21,CA-2014-143336,8/27/2014,9/1/2014,Second Class,ZD-21925,Zuschuss Donatelli,Consumer,United States,San Francisco,California,94109,West,OFF-BI-10002215,Office Supplies,Binders,"Wilson Jones Hanging View Binder, White, 1""",22.7200,4,0.20,7.3840
21,22,CA-2016-137330,12/9/2016,12/13/2016,Standard Class,KB-16585,Ken Black,Corporate,United States,Fremont,Nebraska,68025,Central,OFF-AR-10000246,Office Supplies,Art,Newell 318,19.4600,7,0.00,5.0596
22,23,CA-2016-137330,12/9/2016,12/13/2016,Standard Class,KB-16585,Ken Black,Corporate,United States,Fremont,Nebraska,68025,Central,OFF-AP-10001492,Office Supplies,Appliances,"Acco Six-Outlet Power Strip, 4' Cord Length",60.3400,7,0.00,15.6884
23,24,US-2017-156909,7/16/2017,7/18/2017,Second Class,SF-20065,Sandra Flanagan,Consumer,United States,Philadelphia,Pennsylvania,19140,East,FUR-CH-10002774,Furniture,Chairs,"Global Deluxe Stacking Chair, Gray",71.3720,2,0.30,-1.0196
24,25,CA-2015-106320,9/25/2015,9/30/2015,Standard Class,EB-13870,Emily Burns,Consumer,United States,Orem,Utah,84057,West,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,1044.6300,3,0.00,240.2649
25,26,CA-2016-121755,1/16/2016,1/20/2016,Second Class,EH-13945,Eric Hoffmann,Consumer,United States,Los Angeles,California,90049,West,OFF-BI-10001634,Office Supplies,Binders,Wilson Jones Active Use Binders,11.6480,2,0.20,4.2224
26,27,CA-2016-121755,1/16/2016,1/20/2016,Second Class,EH-13945,Eric Hoffmann,Consumer,United States,Los Angeles,California,90049,West,TEC-AC-10003027,Technology,Accessories,False,90.5700,3,0.00,11.7741
27,28,US-2015-150630,9/17/2015,9/21/2015,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,Pennsylvania,19140,East,FUR-BO-10004834,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",3083.4300,7,0.50,-1665.0522
28,29,US-2015-150630,9/17/2015,9/21/2015,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,Pennsylvania,19140,East,OFF-BI-10000474,Office Supplies,Binders,Avery Recycled Flexi-View Covers for Binding S...,9.6180,2,0.70,-7.0532
29,30,US-2015-150630,9/17/2015,9/21/2015,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,Pennsylvania,19140,East,FUR-FU-10004848,Furniture,Furnishings,"Howard Miller 13-3/4"" Diameter Brushed Chrome ...",124.2000,3,0.20,15.5250
30,31,US-2015-150630,9/17/2015,9/21/2015,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,Pennsylvania,19140,East,OFF-EN-10001509,Office Supplies,Envelopes,Poly String Tie Envelopes,3.2640,2,0.20,1.1016
31,32,US-2015-150630,9/17/2015,9/21/2015,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,Pennsylvania,19140,East,OFF-AR-10004042,Office Supplies,Art,"BOSTON Model 1800 Electric Pencil Sharpeners, ...",86.3040,6,0.20,9.7092
32,33,US-2015-150630,9/17/2015,9/21/2015,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,Pennsylvania,19140,East,OFF-BI-10001525,Office Supplies,Binders,"Acco Pressboard Covers with Storage Hooks, 14 ...",6.8580,6,0.70,-5.7150
33,34,US-2015-150630,9/17/2015,9/21/2015,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,Pennsylvania,19140,East,OFF-AR-10001683,Office Supplies,Art,Lumber Crayons,15.7600,2,0.20,3.5460
34,35,CA-2017-107727,10/19/2017,10/23/2017,Second Class,MA-17560,Matt Abelman,Home Office,United States,Houston,Texas,77095,Central,OFF-PA-10000249,Office Supplies,Paper,Easy-staple paper,29.4720,3,0.20,9.9468
35,36,CA-2016-117590,12/8/2016,12/10/2016,First Class,GH-14485,Gene Hale,Corporate,United States,Richardson,Texas,75080,Central,TEC-PH-10004977,Technology,Phones,GE 30524EE4,1097.5440,7,0.20,123.4737
36,37,CA-2016-117590,12/8/2016,12/10/2016,First Class,GH-14485,Gene Hale,Corporate,United States,Richardson,Texas,75080,Central,FUR-FU-10003664,Furniture,Furnishings,"Electrix Architect's Clamp-On Swing Arm Lamp, ...",190.9200,5,0.60,-147.9630
37,38,CA-2015-117415,12/27/2015,12/31/2015,Standard Class,SN-20710,Steve Nguyen,Home Office,United States,Houston,Texas,77041,Central,OFF-EN-10002986,Office Supplies,Envelopes,"#10-4 1/8"" x 9 1/2"" Premium Diagonal Seam Enve...",113.3280,9,0.20,35.4150
38,39,CA-2015-117415,12/27/2015,12/31/2015,Standard Class,SN-20710,Steve Nguyen,Home Office,United States,Houston,Texas,77041,Central,FUR-BO-10002545,Furniture,Bookcases,"Atlantic Metals Mobile 3-Shelf Bookcases, Cust...",532.3992,3,0.32,-46.9764
39,40,CA-2015-117415,12/27/2015,12/31/2015,Standard Class,SN-20710,Steve Nguyen,Home Office,United States,Houston,Texas,77041,Central,FUR-CH-10004218,Furniture,Chairs,"Global Fabric Manager's Chair, Dark Gray",212.0580,3,0.30,-15.1470
40,41,CA-2015-117415,12/27/2015,12/31/2015,Standard Class,SN-20710,Steve Nguyen,Home Office,United States,Houston,Texas,77041,Central,TEC-PH-10000486,Technology,Phones,Plantronics HL10 Handset Lifter,371.1680,4,0.20,41.7564
41,42,CA-2017-120999,9/10/2017,9/15/2017,Standard Class,LC-16930,Linda Cazamias,Corporate,United States,Naperville,Illinois,60540,Central,TEC-PH-10004093,Technology,Phones,Panasonic Kx-TS550,147.1680,4,0.20,16.5564
42,43,CA-2016-101343,7/17/2016,7/22/2016,Standard Class,RA-19885,Ruben Ausman,Corporate,United States,Los Angeles,California,90049,West,OFF-ST-10003479,Office Supplies,Storage,"Eldon Base for stackable storage shelf, platinum",77.8800,2,0.00,3.8940
43,44,CA-2017-139619,9/19/2017,9/23/2017,Standard Class,ES-14080,Erin Smith,Corporate,United States,Melbourne,Florida,32935,South,OFF-ST-10003282,Office Supplies,Storage,"Advantus 10-Drawer Portable Organizer, Chrome ...",95.6160,2,0.20,9.5616
44,45,CA-2016-118255,3/11/2016,3/13/2016,First Class,ON-18715,Odella Nelson,Corporate,United States,Eagan,Minnesota,55122,Central,TEC-AC-10000171,Technology,Accessories,Verbatim 25 GB 6x Blu-ray Single Layer Recorda...,45.9800,2,0.00,19.7714
45,46,CA-2016-118255,3/11/2016,3/13/2016,First Class,ON-18715,Odella Nelson,Corporate,United States,Eagan,Minnesota,55122,Central,OFF-BI-10003291,Office Supplies,Binders,Wilson Jones Leather-Like Binders with DublLoc...,17.4600,2,0.00,8.2062
46,47,CA-2014-146703,10/20/2014,10/25/2014,Second Class,PO-18865,Patrick O'Donnell,Consumer,United States,Westland,Michigan,48185,Central,OFF-ST-10001713,Office Supplies,Storage,"Gould Plastics 9-Pocket Panel Bin, 18-3/8w x 5...",211.9600,4,0.00,8.4784
47,48,CA-2016-169194,6/20/2016,6/25/2016,Standard Class,LH-16900,Lena Hernandez,Consumer,United States,Dover,Delaware,19901,East,TEC-AC-10002167,Technology,Accessories,False,45.0000,3,0.00,4.9500
48,49,CA-2016-169194,6/20/2016,6/25/2016,Standard Class,LH-16900,Lena Hernandez,Consumer,United States,Dover,Delaware,19901,East,TEC-PH-10003988,Technology,Phones,"LF Elite 3D Dazzle Designer Hard Case Cover, L...",21.8000,2,0.00,6.1040
49,50,CA-2015-115742,4/18/2015,4/22/2015,Standard Class,DP-13000,Darren Powers,Consumer,United States,New Albany,Indiana,47150,Central,OFF-BI-10004410,Office Supplies,Binders,"C-Line Peel & Stick Add-On Filing Pockets, 8-3...",38.2200,6,0.00,17.9634

## Data Analysis

In [6]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Row ID,9994.0,4997.500000,2885.163629,1.000,2499.25000,4997.5000,7495.750,9994.000
Postal Code,9994.0,55190.379428,32063.693350,1040.000,23223.00000,56430.5000,90008.000,99301.000
Sales,9994.0,229.858001,623.245101,0.444,17.28000,54.4900,209.940,22638.480
Quantity,9994.0,3.789574,2.225110,1.000,2.00000,3.0000,5.000,14.000
Discount,9994.0,0.156203,0.206452,0.000,0.00000,0.2000,0.200,0.800
Profit,9994.0,28.656896,234.260108,-6599.978,1.72875,8.6665,29.364,8399.976

In [7]:
df["Product ID"].nunique()

1862

In [8]:
df["Product ID"].value_counts()

OFF-PA-10001970    19
TEC-AC-10003832    18
FUR-FU-10004270    16
FUR-CH-10001146    15
TEC-AC-10003628    15
                   ..
TEC-PH-10003535     1
TEC-MA-10002937     1
OFF-AR-10004974     1
TEC-AC-10004814     1
OFF-ST-10001627     1
Name: Product ID, Length: 1862, dtype: int64

In [9]:
df["Product Name"].value_counts()

False                                                                                  278
Staple envelope                                                                         48
Staples                                                                                 46
Easy-staple paper                                                                       46
Avery Non-Stick Binders                                                                 20
                                                                                      ...
I.R.I.S IRISCard Anywhere 5 Card Scanner                                                 1
Canon Color ImageCLASS MF8580Cdw Wireless Laser All-In-One Printer, Copier, Scanner      1
Xerox 1989                                                                               1
Belkin 7 Outlet SurgeMaster Surge Protector with Phone Protection                        1
Eldon Jumbo ProFile Portable File Boxes Graphite/Black                                   1
Name: Product Name, Length: 1792, dtype: int64

In [10]:
df.loc[df["Product Name"]==False]["Product ID"].unique()

array(['TEC-PH-10002033', 'TEC-AC-10003027', 'TEC-AC-10002167',
       'TEC-AC-10001998', 'TEC-AC-10000844', 'TEC-PH-10000215',
       'TEC-PH-10001254', 'OFF-PA-10000659', 'TEC-AC-10004659',
       'TEC-AC-10003832', 'TEC-PH-10001580', 'OFF-PA-10000673',
       'FUR-CH-10003312', 'OFF-PA-10002713', 'OFF-BI-10002412',
       'TEC-AC-10003911', 'TEC-AC-10004114', 'TEC-AC-10001445',
       'TEC-PH-10002597', 'FUR-TA-10004256', 'TEC-AC-10001267',
       'TEC-PH-10004042', 'OFF-PA-10002137', 'TEC-AC-10002253',
       'TEC-AC-10003610', 'TEC-PH-10001795', 'OFF-PA-10001560',
       'TEC-AC-10001714', 'TEC-PH-10002923', 'TEC-AC-10004666',
       'TEC-PH-10004447', 'OFF-PA-10002870', 'TEC-PH-10003437',
       'OFF-PA-10000466', 'TEC-PH-10004830', 'TEC-AC-10004568',
       'TEC-PH-10004959', 'TEC-AC-10002217', 'TEC-PH-10003811',
       'TEC-PH-10002468', 'TEC-PH-10001578', 'TEC-AC-10000358',
       'TEC-AC-10002637', 'TEC-AC-10000387', 'TEC-AC-10001635',
       'TEC-PH-10003171', 'TEC-PH-10002415', 'TEC-AC-10002305',
       'TEC-AC-10000990', 'TEC-AC-10002558', 'TEC-PH-10004434',
       'TEC-PH-10000193', 'TEC-AC-10004877', 'FUR-FU-10001025',
       'OFF-PA-10003022', 'TEC-AC-10003870', 'TEC-PH-10001468',
       'TEC-AC-10002647'], dtype=object)

In [11]:
df.groupby(["Product ID","Product Name"]).agg({"Quantity": "sum"}).sort_values("Quantity", ascending=False)

                                                                    Quantity
Product ID      Product Name
TEC-AC-10003832 False                                                     75
OFF-BI-10001524 GBC Premium Transparent Covers with Diagonal Li...        67
FUR-CH-10002647 Situations Contoured Folding Chairs, 4/Set                64
FUR-TA-10001095 Chromcraft Round Conference Tables                        61
OFF-BI-10004728 Wilson Jones Turn Tabs Binder Tool for Ring Bin...        59
...                                                                      ...
FUR-BO-10002206 Bush Saratoga Collection 5-Shelf Bookcase, Hano...         1
FUR-CH-10002317 Global Enterprise Series Seating Low-Back Swive...         1
OFF-AR-10002704 Boston 1900 Electric Pencil Sharpener                      1
OFF-PA-10000048 Xerox 20                                                   1
TEC-MA-10003493 Penpower WorldCard Pro Card Scanner                        1

[1893 rows x 1 columns]

In [12]:
df["Order ID"].nunique()

5009

In [13]:
df.groupby("Order ID").agg({"Sales": "sum"})

                   Sales
Order ID
CA-2014-100006   377.970
CA-2014-100090   699.192
CA-2014-100293    91.056
CA-2014-100328     3.928
CA-2014-100363    21.376
...                  ...
US-2017-168802    18.368
US-2017-169320   171.430
US-2017-169488    56.860
US-2017-169502   113.410
US-2017-169551  1344.838

[5009 rows x 1 columns]

In [14]:
df["Price"] = (df["Sales"] + df["Discount"])/df["Quantity"]

In [15]:
df.sort_values("Price", ascending=False).head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Price
2697,2698,CA-2014-145317,3/18/2014,3/23/2014,Standard Class,SM-20320,Sean Miller,Home Office,United States,Jacksonville,Florida,32216,South,TEC-MA-10002412,Technology,Machines,Cisco TelePresence System EX90 Videoconferenci...,22638.480,6,0.5,-1811.0784,3773.163333
6826,6827,CA-2016-118689,10/2/2016,10/9/2016,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Lafayette,Indiana,47905,Central,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.950,5,0.0,8399.9760,3499.990000
4190,4191,CA-2017-166709,11/17/2017,11/22/2017,Standard Class,HL-15040,Hunter Lopez,Consumer,United States,Newark,Delaware,19711,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,10499.970,3,0.0,5039.9856,3499.990000
8153,8154,CA-2017-140151,3/23/2017,3/25/2017,First Class,RB-19360,Raymond Buch,Consumer,United States,Seattle,Washington,98115,West,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.960,4,0.0,6719.9808,3499.990000
2623,2624,CA-2017-127180,10/22/2017,10/24/2017,First Class,TA-21385,Tom Ashbrook,Home Office,United States,New York City,New York,10024,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,11199.968,4,0.2,3919.9888,2800.042000

In [16]:
df.sort_values("Sales", ascending=False).head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Price
2697,2698,CA-2014-145317,3/18/2014,3/23/2014,Standard Class,SM-20320,Sean Miller,Home Office,United States,Jacksonville,Florida,32216,South,TEC-MA-10002412,Technology,Machines,Cisco TelePresence System EX90 Videoconferenci...,22638.480,6,0.5,-1811.0784,3773.163333
6826,6827,CA-2016-118689,10/2/2016,10/9/2016,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Lafayette,Indiana,47905,Central,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.950,5,0.0,8399.9760,3499.990000
8153,8154,CA-2017-140151,3/23/2017,3/25/2017,First Class,RB-19360,Raymond Buch,Consumer,United States,Seattle,Washington,98115,West,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.960,4,0.0,6719.9808,3499.990000
2623,2624,CA-2017-127180,10/22/2017,10/24/2017,First Class,TA-21385,Tom Ashbrook,Home Office,United States,New York City,New York,10024,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,11199.968,4,0.2,3919.9888,2800.042000
4190,4191,CA-2017-166709,11/17/2017,11/22/2017,Standard Class,HL-15040,Hunter Lopez,Consumer,United States,Newark,Delaware,19711,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,10499.970,3,0.0,5039.9856,3499.990000

In [17]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
Price            0
dtype: int64

## Creating RFM metrics

In [18]:
df["Order Date"] = pd.to_datetime(df["Order Date"])

In [19]:
df["Order Date"].max()

Timestamp('2017-12-30 00:00:00')

In [20]:
analysis_date = dt.datetime(2018, 0o1, 0o1)

In [21]:
analysis_date

datetime.datetime(2018, 1, 1, 0, 0)

In [22]:
rfm = df.groupby("Customer ID").agg({"Order Date": lambda OrderDate: (analysis_date - OrderDate.max()).days,
                                    "Order ID": lambda OrderID: OrderID.nunique(),
                                     "Sales": lambda Sales: Sales.sum()})

In [23]:
rfm.head()

             Order Date  Order ID     Sales
Customer ID
AA-10315            186         5  5563.560
AA-10375             21         9  1056.390
AA-10480            261         4  1790.512
AA-10645             57         6  5086.935
AB-10015            417         3   886.156

In [24]:
# The RFM values are generated but it is difficult to compare, therefore RFM scores will be extracted. 
# Monetary is omitted, only recency and frequency are taken into consideration.

rfm.columns = ["recency", "frequency", "monetary"]

In [25]:
# The customer with the recent login is more valuable, so qcut is done in reverse to give the recent ones a higher score.

rfm["recency_score"] = pd.qcut(rfm['recency'], 5, labels=[5, 4, 3, 2, 1])

In [26]:
rfm["frequency_score"] = pd.qcut(rfm['frequency'].rank(method="first"), 5, labels=[1, 2, 3, 4, 5])

In [27]:
rfm["monetary_score"] = pd.qcut(rfm['monetary'], 5, labels=[1, 2, 3, 4, 5])

In [28]:
rfm["RFM_SCORE"] = (rfm['recency_score'].astype(str) + rfm['frequency_score'].astype(str))

rfm.head()

,recency,frequency,monetary,recency_score,frequency_score,monetary_score,RFM_SCORE
Customer ID,,,,,,,
AA-10315,186,5,5563.560,2,2,5,22
AA-10375,21,9,1056.390,5,5,2,55
AA-10480,261,4,1790.512,1,1,3,11
AA-10645,57,6,5086.935,3,3,5,33
AB-10015,417,3,886.156,1,1,1,11

In [29]:
rfm.describe().T

,count,mean,std,min,25%,50%,75%,max
recency,793.0,148.802018,186.211051,2.000,32.00,77.000,185.000,1167.00
frequency,793.0,6.316520,2.550885,1.000,5.00,6.000,8.000,17.00
monetary,793.0,2896.848500,2628.670117,4.833,1146.05,2256.394,3785.276,25043.05

In [30]:
rfm[rfm["RFM_SCORE"] == "55"].head()

,recency,frequency,monetary,recency_score,frequency_score,monetary_score,RFM_SCORE
Customer ID,,,,,,,
AA-10375,21,9,1056.390,5,5,2,55
AH-10210,8,9,4805.344,5,5,5,55
AI-10855,15,10,4375.786,5,5,5,55
AT-10735,15,10,3831.864,5,5,4,55
BF-11170,18,11,5907.972,5,5,5,55

In [31]:
rfm[rfm["RFM_SCORE"] == "11"].head()

,recency,frequency,monetary,recency_score,frequency_score,monetary_score,RFM_SCORE
Customer ID,,,,,,,
AA-10480,261,4,1790.512,1,1,3,11
AB-10015,417,3,886.156,1,1,1,11
AC-10420,234,3,925.800,1,1,1,11
AF-10885,417,4,861.565,1,1,1,11
AG-10525,847,4,1455.038,1,1,2,11

In [32]:
# It will be helpful to create a segment column beside the RFM score. With the help of Regex, the segments are generated.

seg_map = {
    r'[1-2][1-2]': 'hibernating',
    r'[1-2][3-4]': 'at_risk',
    r'[1-2]5': 'cant_loose',
    r'3[1-2]': 'about_to_sleep',
    r'33': 'need_attention',
    r'[3-4][4-5]': 'loyal_customers',
    r'41': 'promising',
    r'51': 'new_customers',
    r'[4-5][2-3]': 'potential_loyalists',
    r'5[4-5]': 'champions'
}

In [33]:
rfm['segment'] = rfm['RFM_SCORE'].replace(seg_map, regex=True)

rfm.head()

,recency,frequency,monetary,recency_score,frequency_score,monetary_score,RFM_SCORE,segment
Customer ID,,,,,,,,
AA-10315,186,5,5563.560,2,2,5,22,hibernating
AA-10375,21,9,1056.390,5,5,2,55,champions
AA-10480,261,4,1790.512,1,1,3,11,hibernating
AA-10645,57,6,5086.935,3,3,5,33,need_attention
AB-10015,417,3,886.156,1,1,1,11,hibernating

In [34]:
# Here are the number of segments and means of each metric in each segment.

rfm[["segment", "recency", "frequency", "monetary"]].groupby("segment").agg(["mean", "count"])

                        recency       frequency           monetary
                           mean count      mean count         mean count
segment
about_to_sleep        75.438596    57  4.000000    57  2486.855437    57
at_risk              225.396226   106  6.566038   106  3099.032902   106
cant_loose           212.871795    39  9.974359    39  4257.519936    39
champions             15.261364    88  9.056818    88  3933.233999    88
hibernating          378.549708   171  3.713450   171  1684.111171   171
loyal_customers       57.812081   149  8.731544   149  3903.655861   149
need_attention        81.000000    32  6.406250    32  2914.021637    32
new_customers         15.863636    22  3.272727    22  1082.290400    22
potential_loyalists   28.321429   112  5.625000   112  2647.323505   112
promising             41.411765    17  3.294118    17  1858.688000    17

In [35]:
rfm[rfm["segment"] == "need_attention"].head()

,recency,frequency,monetary,recency_score,frequency_score,monetary_score,RFM_SCORE,segment
Customer ID,,,,,,,,
AA-10645,57,6,5086.9350,3,3,5,33,need_attention
AG-10675,99,7,3489.0396,3,3,4,33,need_attention
AH-10120,62,7,1735.5140,3,3,2,33,need_attention
AJ-10780,77,7,4867.3440,3,3,5,33,need_attention
AJ-10945,87,7,1839.2400,3,3,3,33,need_attention

In [36]:
# Here are the new customers that may play an important role while creating a marketing strategy. 

rfm[rfm["segment"] == "new_customers"].index

Index(['AH-10585', 'AW-10840', 'AY-10555', 'BD-11635', 'BF-11080', 'BN-11470',
       'CA-12310', 'CM-12115', 'DJ-13630', 'DK-13150', 'EB-13975', 'GD-14590',
       'GH-14665', 'HE-14800', 'JE-16165', 'JH-15430', 'LT-16765', 'PB-18805',
       'RR-19315', 'RS-19870', 'SG-20080', 'SK-19990'],
      dtype='object', name='Customer ID')